### ISSUE TITLE
Number of tokens on file imported, 4x actual?

### ISSUE THREAD

**Issue by david-sg** [minimaxir/gpt-2-simple#25]
With the new 345m version, my dataset tokens has gone from 45k to 184k. 
Is it now tokenizing characters rather than whole words?

**Comment by minimaxir** [comment]
I didn’t change the tokenization at all in the 0.4 release except for `.csv‘ files, where it now handles them by default.

**Comment by david-sg** [comment]
just checked, 63481 tokens as a txt file, 184466 as csv

**Comment by minimaxir** [comment]
So there was a bug that doubled the expected number of tokens, which is now fixed in 0.4.1 and pushed.

In my testing, there's a 1.5x-2x increase in token count from encoding the CSV with the `<|startoftext|>` and `<|endoftext|>` tokens to each text. *However* the source GPT-2 was trained with `<|endoftext|>` tokens: if I use smaller `<|s|>` and `<|e|>` tokens instead, it makes the number of tokens slightly smaller but surprisingly makes the training *substantially* worse.

It may make more sense to just use the `<|endoftext|>` token and an empty start_token, and use `prefix='<|endoftext|>\n` as a parameter when generating, but that's really not great for usability/interpretability (and not necessarily faster). You can do that behavior now by preencoding the CSV with `encode_csv()`, but I'll keep the current behavior for now.
