### ISSUE TITLE
335M model: JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig)

### ISSUE THREAD

**Issue by drusepth** [minimaxir/gpt-2-simple#263]
Whenever I try to fine-tune the 335M model on the Colab notebook, I get the following error:

```python
-
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-44-fd84234416d2> in <module>()
      9               print_every=10,
     10               sample_every=200,
---> 11               save_every=500
     12               )

3 frames
/usr/lib/python3.7/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    336         if s.startswith('\ufeff'):
    337             raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
--> 338                                   s, 0)
    339     else:
    340         if not isinstance(s, (bytes, bytearray)):

JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
```

Obviously this seems like it's the input data's fault, but I confirmed it's in UTF-8 with all byte-order marks removed and still got the issue. I also replaced the entire text file with just a simple repeat of "This is a text file." to meet the sampling length requirements. It also appears when using any of the `sample_data` input files.

Using the 124M model with the same input data (any of the above) works as expected -- I only get the error when fine-tuning the 335M model.

Here's [a Colab notebook showing fine-tuning working on 124M but erroring on 335M](https://colab.research.google.com/drive/1f3RnPVBmoCbd_bvW9MjG6bRZh3Q8OGjW?usp=sharing) with the same input dataset. In case the input gets removed somehow, it's also available in [this gist](https://gist.github.com/drusepth/da24174bb11590eb56d9d0e52e5f03c9) (but I don't think it's specific to this input).

**Comment by frytoli** [comment]
Hi @drusepth. I was having the same issue with the 124M model, and managed to find that the issue was related to the ```model_name``` parameter in my ```finetune``` function call. I do not have access to your Colab notebook, so I can't see if you're falling victim to the same trap.

I had gpt2 download the model to a directory of my choosing, rather than my current directory (as is shown in the [usage example](https://github.com/minimaxir/gpt-2-simple/blob/master/README.md#usage)). In other words, the value of ```model_name``` looked something like this: ```./data/models/124``` rather than just ```124``` (again, see the usage example). Doing this to download the data with the ```download_gpt2()``` method worked fine, but passing this same value to the ```model_name``` param in my ```finetune()``` function call yielded the Json error you specified above. After looking at gpt2's source code (specifically [gpt_2.py](https://github.com/minimaxir/gpt-2-simple/blob/74375a7749f0a037c206a08a17e84f80df269983/gpt_2_simple/gpt_2.py#L127)), I found that ```finetune()``` takes an optional parameter, ```model_dir```, specifically for a path to the models directory that by default is set to ```./models``` (which therefore was telling gpt2 to look in the wrong place for the model). In fact, there are a number of optional parameters that can be passed to this method.

Here is my now-working implementation of the Usage example with the use of additional parameters:
``` python
import gpt_2_simple as gpt2
import os

# Create GPT-2 Path ./gpt2
path_to_gpt2 = os.path.join(path_to_data, 'gpt2')
if not os.path.exists(path_to_gpt2):
    os.mkdir(path_to_gpt2)
# Create GPT-2 Models Path ./gpt2/models
path_to_gpt2_models = os.path.join(path_to_gpt2, 'models')
if not os.path.exists(path_to_gpt2_models):
    os.mkdir(path_to_gpt2_models)
# Create GPT-2 Checkpoints Path ./gpt2/checkpoints
path_to_gpt2_chkpts = os.path.join(path_to_gpt2, 'checkpoints')
if not os.path.exists(path_to_gpt2_chkpts):
    os.mkdir(path_to_gpt2_chkpts)

# Set model name, I want 124M
model_name = '124M'
# If the directory ./gpt2/models/124M does not exist, create it and download the data to the directory
if not os.path.exists(os.path.join(path_to_gpt2_models, model_name)):
    gpt2.download_gpt2(
        model_dir=path_to_gpt2_models, # Set path to models directory: ./gpt2/models
        model_name=model_name          # Specify model name: "124M"
    )

# Start tensorflow session
sess = gpt2.start_tf_sess()

# I have previously downloaded the Shakespeare file to a directory named data: ./data/shakespeare.txt
infile = os.path.join(os.path.getcwd(), 'data',  'shakespeare.txt')

# Finetune the model on our Shakespeare data
gpt2.finetune(
    sess,
    infile,                               # Path to shakespeare.txt -- no special directory parameter needed for this
    model_dir=path_to_gpt2_models,        # Set path to models directory: ./gpt2/models
    model_name=model_name,                # Set model name: "124M"
    checkpoint_dir=path_to_gpt2_chkpts,   # Set path to checkpoints directory: ./gpt2/checkpoints
    steps=1000
)

# Generate some text!
gpt2.generate(sess)
```

I hope that solves your issue too. Do let me know!

**Comment by drusepth** [comment]
Hey @frytoli, thanks for the assist. Unfortunately it didn't look like specifying `model_dir` actually resolved the issue for me, but it did point me in the right direction of what I think the issue is:

I'm just dumb and/or can't read. 

There is no 335M model. The correct model is 355M.

When I called `gpt2.download_gpt2(model_name="335M")`, it completed successfully and downloaded the expected encoder.json, hparams.json, etc, but when you actually look into those files you get the following XML message:

```xml
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:a9660dce-501e-009a-71e8-204216000000
Time:2021-03-24T20:04:23.4431660Z</Message></Error>
```

Trying to load the model is what throws the JSONDecodeError, because these config files are now obviously not JSON. Wasn't related to the input file at all.

Using 355M instead of 335M resolves the issue for me. I'll go ahead and close this now; thanks for the response that got me deep enough debugging to find the problem.
